title: Aman Yadav
logo: assets/aman_logo.png
description: Passionate data scientist with expertise in machine learning, statistical analysis, and data-driven decision making. Experienced in developing end-to-end ML solutions, building predictive models, and creating actionable insights from complex datasets. Strong background in Python programming, statistical modeling, and data visualization with proven track record of delivering business value through data science initiatives.
show_downloads: False
theme: jekyll-theme-minimal
