title: Aman Yadav
logo: assets/aman_logo.png
#Quantitative Researcher & Derivative Analyst with expertise in derivatives markets, statistical arbitrage, and systematic trading strategies. Skilled in developing, backtesting, and deploying quantitative models using Python, financial data APIs, and advanced statistical methods. Experienced in risk management, market microstructure analysis, and portfolio optimization. Currently pursuing advanced studies in Financial Engineering with a strong foundation in econometrics, time series analysis, and machine learning for finance.
show_downloads: False
theme: jekyll-theme-minimal
